server:
  port: 8484
spring:
  profiles:
    active: eagle
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/eaglemap?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  aop:
    proxy-target-class: true
application:
  version: v1.0
eagle:
  timeout: 10000 #请求超时时间，单位：毫秒
  baidu-web-api: https://api.map.baidu.com
  baidu-ying-yan-api: http://yingyan.baidu.com
  amap-web-api: https://restapi.amap.com
  amap-ts-api: https://tsapi.amap.com
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      table-prefix: eagle_
  typeEnumsPackage: cn.itcast.em.enums