server:
  port: 8484 #RESTful服务端口
spring:
  datasource: #数据库的配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/eaglemap?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
eagle:
  #服务模式，可选参数：BASE、COMPLETE，默认：BASE
  #BASE模式中无需配置数据库，只保留基础的地图服务
  service-mode: COMPLETE
  #默认策略，可选参数：BAIDU、AMAP、NONE，默认：NONE
  #如果指定了默认策略，在接口中不指定服务商时才用的策略，如果指定NONE，有系统来决定
  default-provider-strategy: NONE
  baidu-web-api: https://api.map.baidu.com  #百度地图web api服务地址
  baidu-ying-yan-api: http://yingyan.baidu.com #百度地图鹰眼服务地址
  amap-web-api: https://restapi.amap.com #高德地图web api服务地址
  amap-ts-api: https://tsapi.amap.com #高德地图猎鹰服务地址
  admin: #可视化管理系统的配置
    user: eagle #用户名
    password: b09315ea09c6d3b5680094257f1f70e4 #密码，md5加密后
    #RSA的私钥
    private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAKNHw5pK1Jk0EPflxEMFLXa8UnMCTeZoO2NeAtVuu194mxWdDK6W2sdpV1FMD09n8CKg1qV5vOGqj0w2AacSfSxIcOQuloPN2V4r3STdBuIvp35F88WqVqx8pIZ9WvAIRkwcKDkZ87F3X2S+pf7d1crfbyP3PQ7/iTI8dIUtHANdAgMBAAECgYEAhXkTj5weIEKsoEjF39dqq8YUTAmVLoUEDx15iYlkSA3qEIf6JvoQS7Rz+XQIi+u2JEiATnKukXaAf1cikLWPdgA/Su3HqxPjcWuRw/GEBJcwWMaC06wiB1KBUGrqOK5Se193ZSDFU3yWW+jIoYr9IUKFXAbaEco/kgX2lZVzsA0CQQD3dMhQIjBKtbQWPlsIIiNeIuZvfWtjDWokzZLCGbZZgpd+5AABpV550FqqhzCVJdkG7sSRERlCOG9mEjKYRREXAkEAqOr3qp+nX2wP96TIcwPhurcRoPRLbBZHl5iz3E9Akhoi3V8dHapQejUUy9BZswLU853buwdAxADxrcS6nBjPqwJAS1bJ2ePe0hAqKQ+JBZvnKrTzdYQ42qpt45CXGvNbGjtxRlfCTL39Wpb906dfOjmQrtSpEgWjrA6kk+38a3GztwJBAIdYFW+KEtKbREP5rX6yiohPrPlZJKGLTHvEJ8ELY0JtXKghULP3RhpVM7+GxohvaW91eZzm19b0prDD4321R5cCQB8ZNNC7kpgdXvyEOWu7fau9DmTG8e1EWIOEDALaR9w1VpbUIXKprOVURkaMwE00bBE/2fXJBwlteXP2+8L4vMY=
    #RSA的公钥
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCjR8OaStSZNBD35cRDBS12vFJzAk3maDtjXgLVbrtfeJsVnQyultrHaVdRTA9PZ/AioNalebzhqo9MNgGnEn0sSHDkLpaDzdleK90k3QbiL6d+RfPFqlasfKSGfVrwCEZMHCg5GfOxd19kvqX+3dXK328j9z0O/4kyPHSFLRwDXQIDAQAB
    token-time: 24 #token有效期，单位：小时
  timeout: 10000 #请求超时时间，单位：毫秒
  trace-image: #轨迹缩略图
    scale: 0.9 #缩放比，默认0.9
    background: "#FFFFFF" #背景颜色
    trace-color: "#6699FF" #轨迹颜色
    stroke-width: 3 #画笔宽度
    width: 300 #生成图片的宽度
    height: 300 #生成图片的高度
  baidu: #百度相关的配置
    enable: true #是否启用
    name: 百度地图 #服务商的名称
    server: #服务端账号的配置
      id: 25608934
      name: EagleMap-Server
      ak: KurAMXMIh8UaUkGAZjXjz640G2AQQqDk
      type: 服务端
    browser: #浏览器端账号的配置
      id: 25608952
      name: EagleMap-Browser
      ak: dBhLTUDqFj36qTBQ6kestrDgoAn0GcIm
      type: 浏览器端
    trace-servers: #百度地图中的轨迹服务
      - id: 231517
        name: 轨迹服务01
        type: 其他行业
        date: 2022-02-28
      - id: 231518
        name: 轨迹服务02
        type: 其他行业
        date: 2022-02-28
      - id: 231519
        name: 轨迹服务03
        type: 其他行业
        date: 2022-02-28
      - id: 231526
        name: 轨迹服务04
        type: 其他行业
        date: 2022-03-01
  amap: #高德相关的配置
    enable: true #是否启用
    name: 高德地图 #服务商的名称
    server: #服务端账号的配置
      name: EagleMap-Server
      ak: 7488e66ba5375a2b1dba9a154742a2c4
      type: Web服务
    browser: #浏览器端账号的配置
      name: EagleMap-JS
      ak: 65f1bb0520d959878283e5a3721a8be9
      sk: 410148f85c0b68de247373f5d4ba0b39
      type: Web端